GOOGLE_API_KEY = "AIzaSyDfj9-72FgIM5v1CwFSkxMGC8OwLVAzCDs"
SPREADSHEET_ID = "15lvMnpKVP1CVFM-8JTF4k0va5xlqNSNwenFd7N6rtDw"
MENULIST_SPREADSHEET_ID = "15lvMnpKVP1CVFM-8JTF4k0va5xlqNSNwenFd7N6rtDw"

[credentials]
type = "service_account"
project_id = "genial-wonder-444212-g6"
private_key_id = "1fd013bdc834635f35dd2b1feac17c9751ebd27e"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZgJ+A4NyI4Wsb
QkmKNWKLvJUfOPVogbd7gMpPHj6XF10+0OA0T9lvpThyG8HYzaN92K7A3fgDJJCG
wFSXHt2wRknAoikeHnLNfLUyxcAgHjwyWQADdbvGKlmwReQM2LvbJXoZA3MKcmWm
aos+kT8sdv370KqGHznaKDGOB7DifBKPvtetf9RqrUfb4ePgx60uR9bw/iGFmyz2
8I2zNrPhemQo4/KgpxtMK9juwcCQbEneUFiKfV5Y6oLAfsHkuPtaKYxGzAt0DXru
JV+dYZHBPMRXS8X+cqLV0X5pOkydmsmPj30ZtnjKS13I238aC5OevIT7SlbKzyfL
qzir5GKNAgMBAAECggEAANN3S8LjCEX5eCRbKLMvt6VVS897ALW2yqNnfvBMrCUJ
6k9CD8s9sx+K3vbWSwesC5zxPYxZeoA7opRm7O6STIq94414WnvZLAQhjGbjVXGj
6v9VUhXYhpnDakRQfUpMoj3nn7NO401zDsSxWuEvXKBr4c0B3QnaKT8fnbn1H5iy
r6JLvJO0RpmqfUaHIaO0JwclZFxHKGdQJG8svnxOvrPWPY63RWYm04yy/xUWVUIk
B3tE7Wjay6t1cTie1cwWfq8ilYV3LE006KAjc8TJKK9aQlm3+ZQPHgQtjUI++61M
Ie7S06pXzxKxwrwy9WvpNawxikxwbZMZAGAor7/zlQKBgQDK2y9YtKlEjN94Vhhg
agkodgKtSf9QGTBjR0PCCVPg5E1aqSgKs4exE4ra0azY+D5oUOwCmm2taZKKHWIt
EU2aARWg9IAET0k6Xj8qGyC8KFINNcwW7u40x4E+HV/ujnImHZP09vOwDqCPGoiB
VGeYZAGEM8ostCaGnKpBSlolgwKBgQDBt3bI0HZj2s+KXlAZ0zWwNCqsVwf741Tr
J6ACYMIp4HGuaTlAkorGVcwpoJdJ9VsSuYvzCpNjsIju8dTPTmM1vGj06jwpVj9D
NGdH7zour0kbmQkCcM0HOqEE58m4iLgXyg7G9ZR1UuSn3u9YS3g76T6GLteTHuiX
RYWS0CnqrwKBgQCOBKm/Fqwym9WP7+adCV9j/kqde2LNdvUTbD8Zx2H73pnxUOAB
rfLfm+jojUbPl+xJJ+4zXF5Qu8ql+zBSkPydRwkXaFV/rup7fKQIHHnsgOYA7Zr2
q0wFk27+R55z6zIrUSXWqFWu+m6aAV9z+92TKOCO55sxdOZL876WezFldQKBgFND
UTolaA2pejVGLnW7M8Nl2MW0rsjUwKZGpN8AydQIFbTao3IeyqlPLW7jCMQQQrH8
sKupawqZUXIq3caxMbFiJ1bF60/1M0Hmn1HrAH4ad3j2QUocQ/QMfjNGkYzQrxgC
kHFyEvqOw5toFkZEQgy2R1qTfbNNwLlsd2pQMQQfAoGAPosykjz4mvjTT2j1ZFTB
/2NWVKcp//ESAqCvazHVBfSM9OzCfp8+QOCYFeB6buG5EEuaXLpsEaCu7ytnyzDK
sWge+GzYdxNR3LA+Aj+AIWgHtrPxJtoBr8tm3QEtURfdmJbn/7HtzZe0eD/WAJj5
l4ViSHcrPaa+FeQcIZ39v/s=
-----END PRIVATE KEY-----'''
client_email = "google-sheet-174@genial-wonder-444212-g6.iam.gserviceaccount.com"
client_id = "116185125216144985818"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/google-sheet-174%40genial-wonder-444212-g6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
